Homework3
made-mlops-2022/pudyakov_yaroslav_made pull request #2
Opened 2022-12-14 02:45 UTC by boomland

**Важно: start**
Я до этого отправлял по неграмотности дз в личный репозиторий, отправлял инвайт делал пиар и тд. Потом понял свою ошибку, осознал и написал Михаилу в дискорд (сообщение от Pudyakov Yaroslav). Мне разрешили доотправить по-правильному мои сделанные дз, приложив скрины подтверждения. Этот PR полностью совпадает с тем, который я делал ранее, но в нем добавлена спец папка _screenshots_proof/_ в ней есть два файлика с говорящими именами где видно дату посылки + содержимое текста коммита (там расписаны баллы, что подразумевает сопоставлением, что я ничего после коммита не доделывал). Как я понял в переписке, этого должно быть достаточно. Но если вдруг понадобится еще что-то, то я на связи)
Спасибо!
**Важно: end**

Добрый вечер! Сделал все задания из основной части. Бонусы не сделал

0) done (0)
1) done (5)
2) done (10)
3) done (5)
4) done (16)
5) done (1)

Sum = 37
Не уверен что в 4) сумма выставляется, но на всякий случай сделал так

2022-12-27 06:14 UTC, SVizor42 commented on hw3/docker-compose.yml
> +  - AIRFLOW__CORE__LOAD_EXAMPLES=True
Примеры лучше отключить, чтобы не мешали

2022-12-27 06:20 UTC, SVizor42 commented on hw3/dags/train_validate_model_pipeline.py
> +        mounts=[Mount(source="/Users/ypudyakov/prog/made/mlops/MADE_mlops/hw3/data", target="/data", type='bind')]
Пути лучше вынести в константы. К тому же, они неоднократно встречаются

2022-12-27 10:02 UTC, SVizor42 commented on hw3/dags/predict_model_daily.py
> +        command=f"--model_path {Variable.get('MODEL_PATH')} --dataset_data_path {splitted_data_path} --predictions_path {predictions_path} " + "--date {{ ds }}",
При таком варианте часть задач упадет, т.к. предсказание ты пытаешься делать на ежедневной основе, а данные, разбитые на трейн и вал, доступны только по неделям

2022-12-27 10:03 UTC, SVizor42 commented on hw3/dags/data_generator.py
> +    schedule_interval = "@daily",
Проверь форматирование, пробелы вокруг `=` не нужны

2022-12-27 10:06 UTC, SVizor42 requested changes
Комментарии:
1. Убери пжлста лишние папки - `pycache` и `data` (лучше не хранить данные на гите).
2. При оценке пункта 4 варианты не суммируются, а выбирается один из доступных. В твоем случае - это `DockerOperator` (10 баллов).

В остальном, работа - ок.

2022-12-29 02:28 UTC, boomland commented on hw3/dags/predict_model_daily.py
> +        command=f"--model_path {Variable.get('MODEL_PATH')} --dataset_data_path {splitted_data_path} --predictions_path {predictions_path} " + "--date {{ ds }}",
А можно уточнить, почему они по неделям доступны, я вроде специально прописывал генерацию на каждодневной основе? 

```
with DAG(
    dag_id="generate_data_batch", 
    start_date=datetime(2022, 12, 4),
    schedule_interval="@daily",
) as dag:
```

Хочу просто разобраться, вдруг я что-то очевидное не вижу)) Как я понимаю, он каждый день будет генерить пачку данных и класть их в папочку. А потом на основе новых данных будет делать предикт.

2022-12-29 09:43 UTC, boomland commented on hw3/dags/predict_model_daily.py
> +        command=f"--model_path {Variable.get('MODEL_PATH')} --dataset_data_path {splitted_data_path} --predictions_path {predictions_path} " + "--date {{ ds }}",
Сорри, еще не проснусля тогда) До меня дошло, что мне нужно просто предиктить от последней обученной модели. Подправлю)

2022-12-29 13:33 UTC, boomland commented on hw3/docker-compose.yml
> +  - AIRFLOW__CORE__LOAD_EXAMPLES=True
done

2022-12-29 13:34 UTC, boomland commented on hw3/dags/train_validate_model_pipeline.py
> +        mounts=[Mount(source="/Users/ypudyakov/prog/made/mlops/MADE_mlops/hw3/data", target="/data", type='bind')]
done (Сделал конфиг отдельный)

2022-12-29 13:35 UTC, boomland commented on hw3/dags/predict_model_daily.py
> +        command=f"--model_path {Variable.get('MODEL_PATH')} --dataset_data_path {splitted_data_path} --predictions_path {predictions_path} " + "--date {{ ds }}",
done. (Переписал код, сделал так чтобы предикты считались не по расспличенным данным, а по сырым. То есть сначала сырые мы процессим а потом предиктим на них. То есть для предикта даг состоит из двух операций. Скрины обновил - все работает)

2022-12-29 13:35 UTC, boomland commented on hw3/dags/data_generator.py
> +    schedule_interval = "@daily",
done

2022-12-29 13:36 UTC, boomland commented
@SVizor42 
Тимур, подправил все комментарии, жду тогда вердикт/новые комментарии и готов продолжить работу :)

2022-12-30 07:44 UTC, SVizor42 commented on hw3/dags/predict_model_daily.py
> +        command=f"--model_path {Variable.get('MODEL_PATH')} --dataset_data_path {splitted_data_path} --predictions_path {predictions_path} " + "--date {{ ds }}",
Да, инференс условно независимый получается. В идеале, мы должны иметь возможность выбирать любую из доступных/обученных ранее моделей (например, через Airflow Variables)

2022-12-30 07:45 UTC, SVizor42 approved these changes
Теперь хорошо. Можно сливать ветку.

**Сумма: 31 балл**

2022-12-30 11:18 UTC, boomland commented on hw3/dags/predict_model_daily.py
> +        command=f"--model_path {Variable.get('MODEL_PATH')} --dataset_data_path {splitted_data_path} --predictions_path {predictions_path} " + "--date {{ ds }}",
Понял, спасибо!

2022-12-30 11:19 UTC, merged